### ISSUE TITLE
Build is failing with latest paystack adroid library

### ISSUE THREAD

**Issue by darmie** [tolu360/Cordova-Plugin-Paystack#5]
The latest Paystack library seems to be targeting Android API 24, which is affecting ionic build which targets API 22

```
C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\debug\values-v23\values.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'. FAILED

BUILD FAILED

Total time: 59.763 secs


C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\debug\values-v23\values.xml:36: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Android\android-sdk\build-tools\24.0.3\aapt.exe package -f --no-crunch -I C:\Android\android-sdk\platforms\android-22\android.jar -M C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml -S C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\debug -A C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\assets\debug -m -J C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\generated\source\r\debug -F C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\resources-debug.ap_ --debug-mode --custom-package ng.push.userapp -0 apk --output-text-symbols C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\symbols\debug
Error Code:
        1
Output:
        C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\debug\values-v23\values.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

        C:\Users\Damilare\PUSH\mobileapp\platforms\android\build\intermediates\res\debug\values-v23\values.xml:36: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

C:\Users\Damilare\PUSH\mobileapp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                    ^
Error code 1 for command: cmd with args: /s /c "C:\Users\Damilare\PUSH\mobileapp\platforms\android\gradlew cdvBuildDebug -b C:\Users\Damilare\PUSH\mobileapp\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Damilare\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by tolu360** [comment]
Hi @darmie, you just need to update your Android APIs  to at least v24 via the `Android SDK Manager` and you would be fine. Ensure you have the following config or above:

Android SDK Tools: 24+
Android SDK Platform-tools: 24+
Android SDK Build-tools: 24+
SDK Platform: 24+

Run `android` on your terminal to access the `Android SDK Manager`

<img width="694" alt="screen shot 2016-11-04 at 4 35 31 pm" src="https://cloud.githubusercontent.com/assets/3914854/20011972/c2a57f94-a2ad-11e6-8c7c-a421ff906ab9.png">

**Comment by darmie** [comment]
I have all of those. But currently, ionic is targeting API 22

**Comment by tolu360** [comment]
Ionic does not dictate what version of API you build with, you are in control of that. You need a minimum of v24 to use Paystack's SDK, you may need to update your app to match that. Use `cordova build` if you think Ionic has any effect on your build process.

**Comment by darmie** [comment]
Alright
